# Utiliser une image officielle pour FastAPI
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim

# Copier le contenu du répertoire courant dans le conteneur à /app
COPY ./app /app

# Exposer le port 80
EXPOSE 80

# Exécuter le serveur Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
